name: validate-devschema
on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  validate-devschema:
    uses: jdevto/actions/.github/workflows/validate-devschema.yml@main
    with:
      verbose: true
